// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpdPgDecUZC7YXuAvOJHWHsV66ltk3gjA',
    appId: '1:998951769860:web:8ddf06775041e8244e2251',
    messagingSenderId: '998951769860',
    projectId: 'golf-score-app-3d1d8',
    authDomain: 'golf-score-app-3d1d8.firebaseapp.com',
    storageBucket: 'golf-score-app-3d1d8.firebasestorage.app',
    measurementId: 'G-Z6G0JNJ9H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuDgdoOuFeS_nLESRKsx9LZCVHsL9IJ-o',
    appId: '1:998951769860:android:b7ac8a24aafc28744e2251',
    messagingSenderId: '998951769860',
    projectId: 'golf-score-app-3d1d8',
    storageBucket: 'golf-score-app-3d1d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjagqM_tg6P__s2iY5WcX9bw2S0bM0N4U',
    appId: '1:998951769860:ios:76d9437a5724a2334e2251',
    messagingSenderId: '998951769860',
    projectId: 'golf-score-app-3d1d8',
    storageBucket: 'golf-score-app-3d1d8.firebasestorage.app',
    iosBundleId: 'com.chet.golf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjagqM_tg6P__s2iY5WcX9bw2S0bM0N4U',
    appId: '1:998951769860:ios:76d9437a5724a2334e2251',
    messagingSenderId: '998951769860',
    projectId: 'golf-score-app-3d1d8',
    storageBucket: 'golf-score-app-3d1d8.firebasestorage.app',
    iosBundleId: 'com.chet.golf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpdPgDecUZC7YXuAvOJHWHsV66ltk3gjA',
    appId: '1:998951769860:web:c232e62266fdc2664e2251',
    messagingSenderId: '998951769860',
    projectId: 'golf-score-app-3d1d8',
    authDomain: 'golf-score-app-3d1d8.firebaseapp.com',
    storageBucket: 'golf-score-app-3d1d8.firebasestorage.app',
    measurementId: 'G-DB2JGRM66G',
  );
}
